#!/bin/bash
#
# Test script to compare files generated by the old omv-rsnapshot-conf
# shell script vs the new saltstack Jinja2 templates.
#
# Run as root. Both scripts write to the real output paths; results are
# copied to /tmp/rsnapshot-test/{old,new} after each run for diffing.
#
# Usage:
#   sudo bash test-compare-output.sh            # run both, then compare
#   sudo bash test-compare-output.sh --no-salt  # skip salt run
#   sudo bash test-compare-output.sh --no-old   # skip old script run
#   sudo bash test-compare-output.sh --diff-only # just compare existing captures
#

OLD_SCRIPT=${OLD_SCRIPT:-/srv/plugins/old/omv-rsnapshot-conf}

TEST_DIR=/tmp/rsnapshot-test
OLD_OUT=${TEST_DIR}/old
NEW_OUT=${TEST_DIR}/new

ACTUAL_CONFS_DIR=/var/lib/openmediavault/rsnapshot.d
ACTUAL_CRONSCRIPT=/var/lib/openmediavault/cron.d/rsnapshot
ACTUAL_CRON_D=/etc/cron.d/openmediavault-rsnapshot

RUN_OLD=true
RUN_SALT=true

for arg in "$@"; do
    case $arg in
        --no-salt)   RUN_SALT=false ;;
        --no-old)    RUN_OLD=false ;;
        --diff-only) RUN_OLD=false; RUN_SALT=false ;;
    esac
done

capture_files() {
    local dest="$1"
    mkdir -p "${dest}/rsnapshot.d" "${dest}/cron.d"
    ls "${ACTUAL_CONFS_DIR}"/rsnapshot-*.conf &>/dev/null && \
        cp "${ACTUAL_CONFS_DIR}"/rsnapshot-*.conf "${dest}/rsnapshot.d/"
    [ -f "${ACTUAL_CRONSCRIPT}" ] && cp "${ACTUAL_CRONSCRIPT}" "${dest}/cron.d/rsnapshot"
    [ -f "${ACTUAL_CRON_D}" ]    && cp "${ACTUAL_CRON_D}"    "${dest}/cron.d/openmediavault-rsnapshot"
}

run_old() {
    echo "=== Running old omv-rsnapshot-conf ==="
    if [ ! -f "${OLD_SCRIPT}" ]; then
        echo "ERROR: old script not found at ${OLD_SCRIPT}"
        exit 1
    fi
    bash "${OLD_SCRIPT}"
    capture_files "${OLD_OUT}"
    echo "Captured to ${OLD_OUT}"
}

run_salt() {
    echo "=== Running omv-salt deploy run rsnapshot ==="
    omv-salt deploy run rsnapshot
    capture_files "${NEW_OUT}"
    echo "Captured to ${NEW_OUT}"
}

compare_files() {
    echo ""
    echo "======================================================================="
    echo " COMPARISON: old vs new"
    echo "======================================================================="
    local any_diff=false

    # Normalize cron entries: strip comments, collapse whitespace, strip leading zeros
    # from numeric time fields (old script emits "00", new emits "0")
    norm_cron() {
        grep -v '^#' "$1" |
        awk '{for(i=1;i<=5;i++) if($i~/^[0-9]+$/) $i=$i+0; print}' |
        sed 's/[[:space:]]\+/ /g' |
        sed '/^[[:space:]]*$/d'
    }

    # Normalize shell scripts for comparison. The new template intentionally improves
    # over the old script in a few cosmetic ways that are not bugs:
    #   - tabs → spaces indentation
    #   - unquoted [ $var = x ] → quoted [ "$var" = x ]
    #   - trailing spaces inside echo strings removed
    #   - extra blank lines between job blocks
    norm_sh() {
        expand "$1" |
        sed 's/^[[:space:]]*//' |
        sed 's/\[ \$\([a-zA-Z_][a-zA-Z_]*\)/[ "\$\1"/g' |
        sed 's/[[:space:]]*"$/"/g' |
        grep -v '^[[:space:]]*$'
    }

    # --- /etc/cron.d/openmediavault-rsnapshot ---
    # Only compare the cron entries (not headers — old/new use different comment styles)
    echo ""
    echo "--- cron.d/openmediavault-rsnapshot (cron entries only) ---"
    OLD_CRON="${OLD_OUT}/cron.d/openmediavault-rsnapshot"
    NEW_CRON="${NEW_OUT}/cron.d/openmediavault-rsnapshot"
    if [ -f "${OLD_CRON}" ] && [ -f "${NEW_CRON}" ]; then
        diff <(norm_cron "${OLD_CRON}") <(norm_cron "${NEW_CRON}") \
            && echo "  MATCH" || any_diff=true
    else
        [ -f "${OLD_CRON}" ] || echo "  MISSING from old"
        [ -f "${NEW_CRON}" ] || echo "  MISSING from new"
        any_diff=true
    fi

    # --- /var/lib/openmediavault/cron.d/rsnapshot ---
    echo ""
    echo "--- cron.d/rsnapshot (dispatch script) ---"
    OLD_DISPATCH="${OLD_OUT}/cron.d/rsnapshot"
    NEW_DISPATCH="${NEW_OUT}/cron.d/rsnapshot"
    if [ -f "${OLD_DISPATCH}" ] && [ -f "${NEW_DISPATCH}" ]; then
        diff <(norm_sh "${OLD_DISPATCH}") <(norm_sh "${NEW_DISPATCH}") \
            && echo "  MATCH" || any_diff=true
    else
        [ -f "${OLD_DISPATCH}" ] || echo "  MISSING from old"
        [ -f "${NEW_DISPATCH}" ] || echo "  MISSING from new"
        any_diff=true
    fi

    # --- per-job conf files ---
    echo ""
    echo "--- rsnapshot.d/rsnapshot-*.conf ---"
    ALL_UUIDS=$(
        { ls "${OLD_OUT}/rsnapshot.d/"rsnapshot-*.conf 2>/dev/null
          ls "${NEW_OUT}/rsnapshot.d/"rsnapshot-*.conf 2>/dev/null; } |
        sed 's|.*/rsnapshot-||; s|\.conf$||' | sort -u
    )
    for uuid in ${ALL_UUIDS}; do
        OLD_CONF="${OLD_OUT}/rsnapshot.d/rsnapshot-${uuid}.conf"
        NEW_CONF="${NEW_OUT}/rsnapshot.d/rsnapshot-${uuid}.conf"
        echo ""
        echo "  Job: ${uuid}"
        if [ -f "${OLD_CONF}" ] && [ -f "${NEW_CONF}" ]; then
            # Old script emits "# rsnapshot-<uuid>.conf" as first line; new template doesn't
            diff <(grep -v "^# rsnapshot-${uuid}\.conf$" "${OLD_CONF}") \
                 <(grep -v "^# rsnapshot-${uuid}\.conf$" "${NEW_CONF}") \
                && echo "  MATCH" || any_diff=true
        else
            [ -f "${OLD_CONF}" ] || echo "  MISSING from old"
            [ -f "${NEW_CONF}" ] || echo "  MISSING from new"
            any_diff=true
        fi
    done

    echo ""
    echo "======================================================================="
    if ${any_diff}; then
        echo " RESULT: Differences found (see above)"
        return 1
    else
        echo " RESULT: All files match"
    fi
}

mkdir -p "${OLD_OUT}" "${NEW_OUT}"
${RUN_OLD}  && run_old
${RUN_SALT} && run_salt
compare_files
