#!/bin/bash
if [ -z "$1" ]; then
        echo "No argument given. Should be one of: hourly,daily,weekly,monthly,yearly. UUID of backup job can be passed as second argument to execute a single job."
        exit 1
fi
echo "Backups finished."
